projects:
  - id: irond
  - id: ifmapcli
  - id: irongui
  - id: irondhcp
  - id: ironvas
  - id: visitmeta
  - id: ironflow
  - id: ironsyslog
  - id: irontemplate
  - id: irondetect
#  - id: irongenlog
