projects:
  - id: ifmapcli
  - id: irond
  - id: visitmeta

files:
  - source: agendas/szenario-a.txt
    destination: /
  - source: agendas/szenario-b.txt
    destination: /
  - source: agendas/szenario-c.txt
    destination: /
  - source: irond/basicauthusers.properties
    destination: /irond
  - source: visitmeta/dataservice_connections.yml
    destination: /visitmeta/config
  - source: xml/service-discovered-by.xml
    destination: /
  - source: xml/service-implementation.xml
    destination: /
  - source: xml/service-ip.xml
    destination: /
