"TrustAtHsH::Irondemo::Modules::AttackDetected":
  alias: AttackDetected
  config:
    ifmap-user: test
    ifmap-pass: test

"TrustAtHsH::Irondemo::Modules::ImplementationVulnerability":
  alias: ImplementationVulnerability
  config:
    ifmap-user: test
    ifmap-pass: test
    
"TrustAtHsH::Irondemo::Modules::DiscoveredBy":
  alias: DiscoveredBy
  config:
    ifmap-user: test
    ifmap-pass: test

"TrustAtHsH::Irondemo::Modules::ServiceIp":
  alias: ServiceIp
  config:
    ifmap-user: test
    ifmap-pass: test

"TrustAtHsH::Irondemo::Modules::Break":
  alias: Break

"TrustAtHsH::Irondemo::Modules::Nothing":
  alias: Nothing

"TrustAtHsH::Irondemo::Modules::PublishUpdateExample":
  alias: PublishUpdateExample
  config:
    ifmap-user: test
    ifmap-pass: test

"TrustAtHsH::Irondemo::Modules::DeviceIp":
  alias: DeviceIp
  config:
    ifmap-user: test
    ifmap-pass: test

"TrustAtHsH::Irondemo::Modules::AccessRequestIp":
  alias: AccessRequestIp
  config:
    ifmap-user: test
    ifmap-pass: test

"TrustAtHsH::Irondemo::Modules::AccessrequestNCP":
  alias: AccessrequestNCP
  config:
    ifmap-user: test
    ifmap-pass: test

"TrustAtHsH::Irondemo::Modules::AccessrequestDel":
  alias: AccessrequestDel
  config:
    ifmap-user: test
    ifmap-pass: test

"TrustAtHsH::Irondemo::Modules::DeviceConnects":
  alias: DeviceConnects
  config:
    ifmap-user-pdp: pdp
    ifmap-pass-pdp: pdp
    ifmap-user-dhcp: dhcp
    ifmap-pass-dhcp: dhcp

"TrustAtHsH::Irondemo::Modules::DeviceDisconnects":
  alias: DeviceDisconnects
  config:
    ifmap-user-pdp: pdp
    ifmap-pass-pdp: pdp
    ifmap-user-dhcp: dhcp
    ifmap-pass-dhcp: dhcp

"TrustAtHsH::Irondemo::Modules::UserLogin":
  alias: UserLogin
  config:
    ifmap-user: test
    ifmap-pass: test

"TrustAtHsH::Irondemo::Modules::UserLogout":
  alias: UserLogout
  config:
    ifmap-user: test
    ifmap-pass: test

"TrustAtHsH::Irondemo::Modules::LoginFailed":
  alias: LoginFailed
  config:
    ifmap-user: test
    ifmap-pass: test
    
"TrustAtHsH::Irondemo::Modules::LoginSuccess":
  alias: LoginSuccess
  config:
    ifmap-user: test
    ifmap-pass: test
    
"TrustAtHsH::Irondemo::Modules::VulnerabilityDetected":
  alias: VulnerabilityDetected
  config:
    ifmap-user: sensor
    ifmap-pass: sensor

"TrustAtHsH::Irondemo::Modules::InitPdpInfrastructure":
  alias: InitPdpInfrastructure
  config:
    ifmap-user: test
    ifmap-pass: test

"TrustAtHsH::Irondemo::Modules::EnforcementAction":
  alias: EnforcementAction
  config:
    ifmap-user: iptables
    ifmap-pass: iptables

"TrustAtHsH::Irondemo::Modules::PurgeMetadata":
  alias: PurgeMetadata
  config:
    ifmap-user: test
    ifmap-pass: test

"TrustAtHsH::Irondemo::Modules::InvestigationRequested":
  alias: InvestigationRequested
  config:
    ifmap-user: pdp
    ifmap-pass: pdp

"TrustAtHsH::Irondemo::Modules::SmartphoneFeaturesDetected":
  alias: SmartphoneFeaturesDetected
  config:
    ifmap-user: sensor
    ifmap-pass: sensor

"SIMU::SIT::Irondemo::Modules::CreateServerRoom":
  alias: CreateServerRoom
  config:
    ifmap-user: io
    ifmap-pass: io

"SIMU::SIT::Irondemo::Modules::CreateServerRoomA":
  alias: CreateServerRoomA
  config:
    ifmap-user: io
    ifmap-pass: io

"SIMU::SIT::Irondemo::Modules::CreateServerRoomDoor":
  alias: CreateServerRoomDoor
  config:
    ifmap-user: io
    ifmap-pass: io

"SIMU::SIT::Irondemo::Modules::CreateMotionSensor":
  alias: CreateMotionSensor
  config:
    ifmap-user: io
    ifmap-pass: io

"SIMU::SIT::Irondemo::Modules::CreateServerRack":
  alias: CreateServerRack
  config:
    ifmap-user: io
    ifmap-pass: io

"SIMU::SIT::Irondemo::Modules::CreateServer":
  alias: CreateServer
  config:
    ifmap-user: io
    ifmap-pass: io

"SIMU::SIT::Irondemo::Modules::FailedDoorAccessRequest":
  alias: FailedDoorAccessRequest
  config:
    ifmap-user: acs
    ifmap-pass: acs

"SIMU::SIT::Irondemo::Modules::SuccessfulDoorAccessRequest":
  alias: SuccessfulDoorAccessRequest
  config:
    ifmap-user: acs
    ifmap-pass: acs

"SIMU::SIT::Irondemo::Modules::DoorOpenedEvent":
  alias: DoorOpenedEvent
  config:
    ifmap-user: door
    ifmap-pass: door

"SIMU::SIT::Irondemo::Modules::DoorClosedEvent":
  alias: DoorClosedEvent
  config:
    ifmap-user: door
    ifmap-pass: door

"SIMU::SIT::Irondemo::Modules::MotionDetectedEvent":
  alias: MotionDetectedEvent
  config:
    ifmap-user: motion
    ifmap-pass: motion

"SIMU::SIT::Irondemo::Modules::FailedRackAccessRequest":
  alias: FailedRackAccessRequest
  config:
    ifmap-user: acs
    ifmap-pass: acs

"SIMU::SIT::Irondemo::Modules::SuccessfulRackAccessRequest":
  alias: SuccessfulRackAccessRequest
  config:
    ifmap-user: acs
    ifmap-pass: acs

"SIMU::SIT::Irondemo::Modules::ServerConnectedEvent":
  alias: ServerConnectedEvent
  config:
    ifmap-user: kvm
    ifmap-pass: kvm

"SIMU::SIT::Irondemo::Modules::ServerDisconnectedEvent":
  alias: ServerDisconnectedEvent
  config:
    ifmap-user: kvm
    ifmap-pass: kvm

"SIMU::SIT::Irondemo::Modules::DeviceDetected":
  alias: DeviceDetected
  config:
    ifmap-user: io
    ifmap-pass: io

"SIMU::SIT::Irondemo::Modules::DeviceConnectionDetected":
  alias: DeviceConnectionDetected
  config:
    ifmap-user: io
    ifmap-pass: io

"SIMU::SIT::Irondemo::Modules::AddInterfaceToDevice":
  alias: AddInterfaceToDevice
  config:
    ifmap-user: io
    ifmap-pass: io

"SIMU::SIT::Irondemo::Modules::AddAddressToInterface":
  alias: AddAddressToInterface
  config:
    ifmap-user: io
    ifmap-pass: io

"SIMU::SIT::Irondemo::Modules::AddNetworkToAddress":
  alias: AddNetworkToAddress
  config:
    ifmap-user: io
    ifmap-pass: io

"SIMU::SIT::Irondemo::Modules::LinkAddresses":
  alias: LinkAddresses
  config:
    ifmap-user: io
    ifmap-pass: io

"SIMU::Macmon::Irondemo::Modules::InitPdp":
  alias: MacmonInitPdp
  config:
    ifmap-user: macmon
    ifmap-pass: macmon
    pep-device: macmon:83vk-934v-2134
    pep-ip: 192.168.100.1
    administrative-domain: simu.de
    macmon-service-name: macmon
    macmon-service-type: nac
    macmon-service-port: 4443
    macmon-implementation-value: macmon
    macmon-implementation-version: 4.2.0

"SIMU::Macmon::Irondemo::Modules::EndpointOnline":
  alias: MacmonEndpointOnline
  config:
    ifmap-user: macmon
    ifmap-pass: macmon
    pep-device: macmon:83vk-934v-2134
    discovery-method: NMAP

"SIMU::Macmon::Irondemo::Modules::EndpointService":
  alias: MacmonEndpointService
  config:
    ifmap-user: macmon
    ifmap-pass: macmon
    pep-device: macmon:83vk-934v-2134
    administrative-domain: simu.de

