#<id>
#  sources:
#    scm: <git>
#    uri: <uri>
#  build:
#    tool: <mvn>
#    commands:
#      - <list of commands>
#  binaries:
#    directories:
#      - directory:
#        source: 
#          path:
#          match:
#        destination:
#          path:
#          rename:
#    archives:
#      -archive:
#        source: 
#          path:
#          match:
#        destination:
#          path:
#          rename:
#    files:
#      - file
#        source: 
#          path:
#          match:
#        destination:
#          path:
#          rename:
#  executable_dir:

irond:
  sources:
    scm: git
    uri: http://github.com/trustathsh/irond.git
  build: 
    tool: mvn
    commands:
      - mvn package
  binaries:
    archives:
      - archive: 
        source: 
          path: target
          match: irond-(\d+\.)?(\d+\.)?(\d+)-bundle\.zip$
        destination:
          path: /
          rename: irond
  executable_dir: irond

ifmapj:
  sources:
    scm: git
    uri: http://github.com/trustathsh/ifmapj.git
  build: 
    tool: mvn
    commands:
      - mvn package

ifmapj-examples:
  sources:
    scm: git
    uri: http://github.com/trustathsh/ifmapj-examples.git
  build: 
    tool: mvn
    commands:
      - mvn package

ifmapcli:
  sources:
    scm: git
    uri: http://github.com/trustathsh/ifmapcli.git
  build: 
    tool: mvn
    commands:
      - mvn package
  binaries:
    archives:
      - archive:
        source:
          path: ifmapcli-distribution/target
          match: ifmapcli-distribution-(\d+\.)?(\d+\.)?(\d+)-bundle\.zip
        destination:
          path: /
          rename: ifmapcli
  executables_dir: ifmapcli

irongui:
  sources:
    scm: git
    uri: http://github.com/trustathsh/irongui.git
  build: 
    tool: mvn
    commands:
      - mvn package
  binaries: 
    archives:
      - archive:
        source:
          path: target
          match: irongui-(\d+\.)?(\d+\.)?(\d+)-bundle\.zip
        destination:
          path: /
          rename: irongui
  executable_dir: irongui

irondetect:
  sources:
    scm: git
    uri: http://github.com/trustathsh/irondetect.git
  build: 
    tool: mvn
    commands:
      - mvn package
  binaries: 
    archives:
      - archive:
        source:
          path: target
          match: irondetect-(\d+\.)?(\d+\.)?(\d+)-bundle\.zip
        destination:
          path: /
          rename: irondetect
  executable_dir: irondetect

irondhcp:
  sources:
    scm: git
    uri: http://github.com/trustathsh/irondhcp.git
  build: 
    tool: mvn
    commands:
      - mvn package
  binaries: 
    archives:
      - archive:
        source:
          path: target
          match: irondhcp-(\d+\.)?(\d+\.)?(\d+)-bundle\.zip
        destination:
          path: /
          rename: irondhcp
  executable_dir: irondhcp

ironvas:
  sources:
    scm: git
    uri: http://github.com/trustathsh/ironvas.git
  build:
    tool: mvn
    commands:
     - mvn package
  binaries: 
    archives:
      - archive:
        source:
          path: target
          match: ironvas-(\d+\.)?(\d+\.)?(\d+)-bundle\.zip
        destination:
          path: /
          rename: ironvas
  executable_dir: ironvas

visitmeta:
  sources:
    scm: git
    uri: https://github.com/trustathsh/visitmeta.git
  build:
    tool: mvn
    commands:
     - mvn package
  binaries: 
    archives:
      - archive:
        source:
          path: visitmeta-distribution/target
          match: visitmeta-distribution-(\d+\.)?(\d+\.)?(\d+)-bundle\.zip
        destination:
          path: /
          rename: visitmeta
  executable_dir: visitmeta

ironflow:
  sources:
    scm: git
    uri: http://github.com/trustathsh/ironflow.git
  build:
    tool: mvn
    commands:
     - mvn package
  binaries: 
    archives:
      - archive:
        source:
          path: target
          match: ironflow-(\d+\.)?(\d+\.)?(\d+)-bundle\.zip
        destination:
          path: /
          rename: ironflow
  executable_dir: ironflow

ironsyslog:
  sources:
    scm: git
    uri: http://github.com/trustathsh/ironsyslog.git
  build:
    tool: mvn
    commands:
     - mvn package
  binaries: 
    archives:
      - archive:
        source:
          path: target
          match: ironsyslog-(\d+\.)?(\d+\.)?(\d+)-bundle\.zip
        destination:
          path: /
          rename: ironsyslog
  executable_dir: ironsyslog

irontemplate:
  sources:
    scm: git
    uri: http://github.com/trustathsh/irontemplate.git
  build:
    tool: mvn
    commands:
     - mvn package
  binaries: 
    archives:
      - archive:
        source:
          path: target
          match: irontemplate-(\d+\.)?(\d+\.)?(\d+)-bundle\.zip
        destination:
          path: /
          rename: irontemplate
  executable_dir: irontemplate

irongenlog:
  sources:
    scm: git
    uri: http://github.com/trustathsh/irongenlog.git
  build:
    tool: mvn
    commands:
     - mvn package
  binaries: 
    archives:
      - archive:
        source:
          path: target
          match: irongenlog-(\d+\.)?(\d+\.)?(\d+)-bundle\.zip
        destination:
          path: /
          rename: irongenlog
  executable_dir: irongenlog
